### ISSUE TITLE
Feature request - Support for AWS GPU

### ISSUE THREAD

**Issue by tristandostaler** [OkiokData/SmartHashCat#8]
I think it could be cool to have a script to automatically deploy an AWS GPU machine, automatically install SHC and launch it automatically. You would only need to provide an AWS API key or something like that.
I am thinking something along the line of "SmartHashCat.py -n Example -u https://www.example.com -f hashes.txt --aws-key safdasdsafdfdssf"

**Comment by tristandostaler** [comment]
Proposition started in https://github.com/tristandostaler/SmartHashCat/tree/feature/aws-gpu

**Comment by yaap7** [comment]
I think it would be cool to have this feature, however I'm not sure it should be merge inside SmartHashCat internals.

If I have a simple laptop without any cracking power, maybe even running Windows 10 for example, I would like to deploy an AWS instance to install SmartHashCat on. But I don't want to install SHC on my Windows 10 laptop (I even cannot do it since it works only on GNU/Linux) just to launch a script to deploy SHC on another system. Does it make sense?

Maybe it should be integrated in an external script, like a "smarthashcat-utils" ?
Or, at least, if it is incorporated into SHC, it should not need SHC to be completely installed on the laptop imho.

**Comment by tristandostaler** [comment]
I think that makes perfect sense and didn't think about it that way 

On this 2 things.
1. I have in mind to eventually port it to windows. All dependencies work on windows so it's just a mather to change some logic
2. The aws logic would work on windows as long as you have python without installing it (not at the moment but that's a simple change). I'll add this to my todo i think to make this part os agnostic

**Comment by mlahaye811** [comment]
I close it as it should not be integrated in SmartHashCat(-core).

**Comment by tristandostaler** [comment]
So more as a deployToAWS.py script?

**Comment by tristandostaler** [comment]
FYI I am done with this feature. We just need to find how to use it. It's a python script
